### ISSUE TITLE
Needs app.js file.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/api-token-auth#14]
We created this in class.

**Comment by gaand** [comment]
This is part of the scaffolding for the lesson.  A place to keep application information and state, e.g.

api url
info about signed in user.

**Comment by gaand** [comment]
@payne-chris-r I added it in 0dc70092cdceb5757dc8cb303a94abf28438d48a

Please close.  Thanks.

**Comment by payne-chris-r** [comment]
Thanks Antony.
