### ISSUE TITLE
Importance of Auth and why we care

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/api-token-auth#15]
@gaand and @jrhorn424 both came up to me after this lesson and mentioned that the lesson left out a good bit of the "why" and focused mostly on the "how." I agree that this is important, but also looked back and noticed that it doesn't exist at all in the README. It should be added. If not by them, than by whoever delivers this next.

**Comment by gaand** [comment]
It's not something that needs to be called out in a big way in the readme, but it is something to talk about with the developers.

So, I see it's a lesson about auth and know the topic is something to chat about.

It might be as simple as adding a line at the top of the `Using web APIs` section along the lines:

> Why do we need to learn about auth.  Why is this an important topic. 

@payne-chris-r If that's not enough then we should consider how to handle instructional notes (I thought we had an issue about this, but I can't find it so I'll open one).
